### ISSUE TITLE
data and web containers are in continues Restarting state

### ISSUE THREAD

**Issue by slyapustin** [realpython/dockerizing-django#19]
Can't create working example, using instructions form Readme file.

> docker-compose ps
> ##             Name                          Command                 State              Ports
> 
> dockerizingdjango_data_1       /docker-entrypoint.sh true       Restarting   5432/tcp
> dockerizingdjango_nginx_1      /usr/sbin/nginx                  Up           0.0.0.0:80->80/tcp
> dockerizingdjango_postgres_1   /docker-entrypoint.sh postgres   Up           0.0.0.0:5432->5432/tcp
> dockerizingdjango_redis_1      /entrypoint.sh redis-server      Up           0.0.0.0:6379->6379/tcp
> dockerizingdjango_web_1        /usr/local/bin/gunicorn do ...   Restarting   8000/tcp

Output of `docker-compose logs` is:

> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [1] [INFO] Starting gunicorn 19.3.0
> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [1] [INFO] Using worker: sync
> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [8] [INFO] Booting worker with pid: 8
> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [8] [ERROR] Exception in worker process:
> ←[33mweb_1      | ←[0mTraceback (most recent call last):
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
> ←[33mweb_1      | ←[0m    worker.init_process()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 118, in init_process
> ←[33mweb_1      | ←[0m    self.wsgi = self.app.wsgi()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
> ←[33mweb_1      | ←[0m    self.callable = self.load()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
> ←[33mweb_1      | ←[0m    return self.load_wsgiapp()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
> ←[33mweb_1      | ←[0m    return util.import_app(self.app_uri)
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 355, in import_app
> ←[33mweb_1      | ←[0m    **import**(module)
> ←[33mweb_1      | ←[0mImportError: No module named 'docker_django'
> ←[33mweb_1      | ←[0mTraceback (most recent call last):
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
> ←[33mweb_1      | ←[0m    worker.init_process()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 118, in init_process
> ←[33mweb_1      | ←[0m    self.wsgi = self.app.wsgi()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
> ←[33mweb_1      | ←[0m    self.callable = self.load()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
> ←[33mweb_1      | ←[0m    return self.load_wsgiapp()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
> ←[33mweb_1      | ←[0m    return util.import_app(self.app_uri)
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 355, in import_app
> ←[33mweb_1      | ←[0m    **import**(module)
> ←[33mweb_1      | ←[0mImportError: No module named 'docker_django'
> ←[33mweb_1      | ←[0m[2016-02-22 16:59:05 +0000] [8] [INFO] Worker exiting (pid: 8)
> ←[33mweb_1      | ←[0mTraceback (most recent call last):
> ←[33mweb_1      | ←[0m  File "/usr/local/bin/gunicorn", line 11, in <module>
> ←[33mweb_1      | ←[0m    sys.exit(run())
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
> ←[33mweb_1      | ←[0m    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 189, in run
> ←[33mweb_1      | ←[0m    super(Application, self).run()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
> ←[33mweb_1      | ←[0m    Arbiter(self).run()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 174, in run
> ←[33mweb_1      | ←[0m    self.manage_workers()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
> ←[33mweb_1      | ←[0m    self.spawn_workers()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
> ←[33mweb_1      | ←[0m    time.sleep(0.1 \* random.random())
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
> ←[33mweb_1      | ←[0m    self.reap_workers()
> ←[33mweb_1      | ←[0m  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
> ←[33mweb_1      | ←[0m    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
> ←[33mweb_1      | ←[0mgunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
> ←[31mERROR←[0m: Aborting.

**Comment by mjhea0** [comment]
There's a number of solutions to that in the comment section of the blog post. Also, check out https://github.com/docker/compose/issues/1013.

**Comment by s7726** [comment]
Should the blogpost or the instructions in the readme be updated to include the --rm solution? I ran into the same thing. Also it looks like the data volume does not need restart always, since it doesn't really need to run.

**Comment by mjhea0** [comment]
Possibly. Want to issue a PR?

**Comment by myhat123** [comment]
if docker-machine begin to run, django does not work.
compose logs:
ImportError: No module named 'docker_django'

but after docker-machine do not run, "docker-compose up" is right, dockerizing_django web is very nice.

why?

**Comment by mjhea0** [comment]
You are asking why you have to create a Docker Machine before you run `docker compose up`?

**Comment by myhat123** [comment]
After docker machine start, execute 
"docker compose up", show error message:
ImportError: No module named 'docker_django'

**Comment by mjhea0** [comment]
Did you clone my repo exactly? Which versions of Python, Docker Machine, Docker Compose, and Django are you using?

**Comment by slyapustin** [comment]
The problem is in adding volumes here:
https://github.com/realpython/dockerizing-django/blob/master/docker-compose.yml#L9

Because, you using `python:3.5-onbuild` for building `web` image and it has already copied all project data:

> ONBUILD COPY . /usr/src/app
> https://github.com/docker-library/python/blob/master/3.5/onbuild/Dockerfile#L9

You should consider removing all `volumes` entries form `web` in your main docker-compose.yml file:
https://github.com/realpython/dockerizing-django/blob/master/docker-compose.yml#L9

**Comment by mjhea0** [comment]
@inoks Want to create an example docker-compose.yml file?

**Comment by slyapustin** [comment]
Here PR:
https://github.com/realpython/dockerizing-django/pull/20

**Comment by slyapustin** [comment]
Coupe of things from comments in PR, which need to be mentioned in Readme:

1) using docker exec, instead of docker run command
2) mounting host folders https://docs.docker.com/v1.8/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume
