### ISSUE TITLE
static volume

### ISSUE THREAD

**Issue by oppianmatt** [realpython/dockerizing-django#23]
in production you have a static volume for the statics like in dev. But how does this scale to N hosts?

Isn't this against the docker container philosophy now that you are maintaining state? If I need to put the app container on multiple hosts who controls the static?  How does it get to the nginx host?

What do you think instead of putting collectstatic into the dockerfile and serving static content with whitenoise?

**Comment by mjhea0** [comment]
Yes, just add `RUN python manage.py collectstatic —noinput` to the Dockerfile.
