### ISSUE TITLE
failed to manage.py migrate

### ISSUE THREAD

**Issue by sephib** [realpython/dockerizing-django#30]
Hi,
I'm running your example on windows10.
When I run the 
docker-compose run -d web /usr/local/bin/python manage.py migrate
I get an 
ERROR: Container command 'C:/Program Files/Git/usr/local/bin/python' not found or does not exist.

My workaround was to run
docker-compose run -d web python manage.py migrate

FYI

**Comment by mjhea0** [comment]
Thank you!
