### ISSUE TITLE
standard admin page?

### ISSUE THREAD

**Issue by rochford77** [realpython/dockerizing-django#43]
is there a way to get the standard admin page. I followed the blog post and everything works well, however the django admin page is wonky.
![screen shot 2017-02-01 at 11 47 07 pm](https://cloud.githubusercontent.com/assets/10854970/22537473/dd3a01ec-e8d8-11e6-95cd-d0eceb40d7f9.png)

**Comment by vstoykov** [comment]
There is not a problem with the admin page. There is a problem with serving the static files from your project.

**Comment by jujes** [comment]
yes, use this command:

```
docker-compose exec web python manage.py collectstatic --noinput
```

**Comment by rochford77** [comment]
WOW, didn't even consider that. I'll Give it a shot this evening.

**Comment by AliYmn** [comment]
@jujes  thanks.
