### ISSUE TITLE
postgres conflict (5432: bind: address already in use)

### ISSUE THREAD

**Issue by ghost** [realpython/dockerizing-django#45]
Gentlemen,
i was following up with the article (https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/), when i suddenly could not continue because of an error related to postgres image creation.
i have clones the online repository from github, using the link provided inside the article. i have followed the instructions. i could do "docker-compose build" successfully, but i couldn't do "docker-compose up -d", it is stopping on the level of postgres and giving the following error:

"ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint dockerizingdjango_postgres_1 (e52b1c5ae30c7398a7daf5254cea43b61567b52fae2da2e25fa7fd903d7bc516): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use"
"ERROR: Encountered errors while bringing up the project."

i have read a over the internet, especially in the official documentation of postgres, that it is a conflict with the ports. 
so i have already postgresql installed locally on my laptop and i use usually "virtualenv" to work with django. i install psycopg2 inside the "virtualenv" and everything will work well.
now, back to this article, when i couldn't do "docker-compose up -d", i did "docker run -it postgres:latest" trying to interact with the image directly, it gave me a log hint:
[
waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  database system was shut down at 2017-05-04 17:07:18 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
ALTER ROLE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
waiting for server to shut down....LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2017-05-04 17:07:20 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
]
Question: 
is it really a matter of ports, or something else?

thank you

**Comment by mjhea0** [comment]
Yes, this is a port conflict. Try changing the port in your docker-compose file as well as within django settings.
