### ISSUE TITLE
postgres .env

### ISSUE THREAD

**Issue by AliYmn** [realpython/dockerizing-django#46]
Hi,
https://github.com/realpython/dockerizing-django/blob/master/.env I get an error when I change the information in the .env file.

example ;

    # Add Environment Variables
    SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
    DB_NAME=djangoproject
    DB_USER=admin
    DB_PASS=adminpass
    DB_SERVICE=postgres
    DB_PORT=5432

How should I do?

    web_1       | django.db.utils.OperationalError: FATAL:  role "admin" does not exist
    web_1       | 
    postgres_1  | FATAL:  role "admin" does not exist
    postgres_1  | FATAL:  role "admin" does not exist

Details error : https://hastebin.com/egidekidin.sql

**Comment by mjhea0** [comment]
You will need to create the role before doing anything else. After the container is spun up, before you apply the migrations you will need to create the role. 

https://github.com/realpython/flask-microservices-main/blob/master/docker-compose.yml#L11

**Comment by AliYmn** [comment]
Is it true?
https://gist.github.com/AliYmn/ce4e3075090a05753d9df328a0155fe1#file-docker-compose-yml-L33

Do I have to do something else?

**Comment by mjhea0** [comment]
Change it to match the username and password you're using in your *.env* file.

**Comment by AliYmn** [comment]
docker-compose.yml ;
https://gist.github.com/AliYmn/ce4e3075090a05753d9df328a0155fe1#file-docker-compose-yml-L34

.env file;
https://gist.github.com/AliYmn/66498d8bcadb831b8ef81a471b77fc15#file-env-L5

result error ;

https://hastebin.com/akedebidop.rb

**Comment by mjhea0** [comment]
Make sure you rebuild the containers. You could also create the role manually with a sql script that is added to the entrypoint folder: https://stackoverflow.com/questions/26598738/how-to-create-user-database-in-script-for-docker-postgres

**Comment by AliYmn** [comment]
The problem was solved after it was built.
Thank you so much.

**Comment by AliYmn** [comment]
I'd like to ask you something else if you let me.
I established another site with Docker (port: 8001). But I got a postgres error, why?
Also, I can not build a second new database.

**Comment by mjhea0** [comment]
Depends on the error. Sorry, but I cannot offer any more support. GitHub issues is not the right venue for this. Please post your questions on StackOverflow.

I also suggest going through some Docker basics:

- https://docs.docker.com/get-started/
- http://mherman.org/docker-workshop/#1

Once you get the basics down and you want to learn more about linking multiple services together, check out http://testdriven.io/
