### ISSUE TITLE
Programming Error relation "todo_item" does not exist

### ISSUE THREAD

**Issue by inquilabee** [realpython/dockerizing-django#61]
I did all the steps as described in https://realpython.com/django-development-with-docker-compose-and-machine/ and after running `docker-compose run web /usr/local/bin/python manage.py migrate` and going to `192.168.99.100` on my browser, 

ProgrammingError at /

relation "todo_item" does not exist
LINE 1: ...todo_item"."text", "todo_item"."date_posted" FROM "todo_item.

docker-compose logs gives me the following

postgres_1  | 2019-06-23 19:44:45.120 UTC [36] STATEMENT:  SELECT "todo_item"."id", "todo_item"."text", "todo_item"."date_posted" FROM "todo_item"  LIMIT 21

Any idea where I might have gone wrong?

**Comment by fasouto** [comment]
I ran into the same problem, seems like there's no migrations for the `todo` app. I fixed it creating the migrations for the todo app first:

```
docker-compose exec web /usr/local/bin/python manage.py makemigrations todo
```
then I apply those migrations:
```
docker-compose exec web /usr/local/bin/python manage.py migrate 
```
